### ISSUE TITLE
Elke standaard is zo goed als z'n toepassing in de praktijk. Hoe borgt DIZRA haar toepassing? Speelt de Handreiking "USM voor DIZRA" daar een rol bij?

### ISSUE THREAD

**Issue by jvbon** [minvws/dizra-docs#11]

**Comment by jvbon** [comment]
Dit heeft betrekking op de vraag of we laag 2 uit het vijflaagsmodel ook willen ondersteunen met structuuraanbevelingen om de toepasbaarheid en benutting van DIZRA te bevorderen.

**Comment by hietkamp** [comment]
We moeten eerst weten over welke toepassing we het hebben. 

We zien het informatiestelsel als een stelsel van standaarden. Deze standaarden  beschrijven de normen voor gegevensuitwisseling tussen deelnemers. Op basis van deze normen worden technische afspraken gemaakt voor een voorziening (een applicatie) van een actor in een systeemrol. Al dan niet voorzieningen die ingekocht kunnen worden, gemeenschappelijke voorzieningen of publieke voorzieningen. Samen moeten deze voorzieningen een ecosysteem vormen voor gegevensuitwisseling in de zorg.

De deelnemers implementeren de voorzieningen voor de systeemrollen die zij vervullen. 

DIZRA wordt toegepast voor het realiseren van samenhang en voor het maken van keuzes in het informatiestelsel. De toepassing van DIZRA is vooral bij het maken van de informatiestandaarden en de technische afspraken. En vervolgens in de implementatie van deze informatiestandaarden in voorzieningen.

Een deelnemer (bijvoorbeeld een zorgorganisatie) moet voor haar organisatie de samenwerkingsafspraken en processtandaarden implementeren en hanteren. Waarbij ook het gebruik van de voorzieningen geborgd moet zijn zodat de deelnemer haar dienstverlening kan verbeteren en de kwaliteit en continuïteit van zorg kan verhogen c.q. borgen. Voor het implementeren van deze samenwerkingsafspraken, processtandaarden en voorzieningen kan USM een rol spelen.
